export const PLANETS = [
  {
    id: "1",
    englishName: "Mercury",
    name: "Mercurio",
    mass: { massValue: 3.285e23 },
    meanRadius: 2439.7,
    density: 5.427,
    gravity: 3.7,
    avgTemp: 440,
    semimajorAxis: 57909227,
    inclination: 7,
    moons: [{ moon: "Luna" }],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "2",
    englishName: "Venus",
    name: "Venus",
    mass: { massValue: 4.867e24 },
    meanRadius: 6051.8,
    density: 5.243,
    gravity: 8.87,
    avgTemp: 737,
    semimajorAxis: 108209475,
    inclination: 3.39,
    moons: [],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "3",
    englishName: "Earth",
    name: "Tierra",
    mass: { massValue: 5.97219e24 },
    meanRadius: 6371,
    density: 5.513,
    gravity: 9.81,
    avgTemp: 288,
    semimajorAxis: 149598262,
    inclination: 0,
    moons: [{ moon: "Luna" }],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "4",
    englishName: "Mars",
    name: "Marte",
    mass: { massValue: 6.39e23 },
    meanRadius: 3389.5,
    density: 3.9335,
    gravity: 3.71,
    avgTemp: 210,
    semimajorAxis: 227943824,
    inclination: 1.85,
    moons: [{ moon: "Fobos" }, { moon: "Deimos" }],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "5",
    englishName: "Jupiter",
    name: "Júpiter",
    mass: { massValue: 1.898e27 },
    meanRadius: 69911,
    density: 1.33,
    gravity: 24.79,
    avgTemp: 165,
    semimajorAxis: 778340821,
    inclination: 1.305,
    moons: [
      { moon: "Io" },
      { moon: "Europa" },
      { moon: "Ganímedes" },
      { moon: "Calisto" },
    ],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "6",
    englishName: "Saturn",
    name: "Saturno",
    mass: { massValue: 5.683e26 },
    meanRadius: 58232,
    density: 0.687,
    gravity: 10.44,
    avgTemp: 134,
    semimajorAxis: 1426666422,
    inclination: 2.485,
    moons: [
      { moon: "Mimas" },
      { moon: "Encélado" },
      { moon: "Tetis" },
      { moon: "Dione" },
      { moon: "Rea" },
      { moon: "Titán" },
      { moon: "Jápeto" },
    ],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "7",
    englishName: "Uranus",
    name: "Urano",
    mass: { massValue: 8.681e25 },
    meanRadius: 25362,
    density: 1.27,
    gravity: 8.69,
    avgTemp: 76,
    semimajorAxis: 2870658186,
    inclination: 0.772,
    moons: [
      { moon: "Ariel" },
      { moon: "Umbriel" },
      { moon: "Titania" },
      { moon: "Oberón" },
      { moon: "Miranda" },
    ],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
  {
    id: "8",
    englishName: "Neptune",
    name: "Neptuno",
    mass: { massValue: 1.024e26 },
    meanRadius: 24622,
    density: 1.638,
    gravity: 11.15,
    avgTemp: 72,
    semimajorAxis: 4498396441,
    inclination: 1.769,
    moons: [
      { moon: "Tritón" },
      { moon: "Nereida" },
      { moon: "Náyade" },
      { moon: "Talasa" },
      { moon: "Despina" },
      { moon: "Galatea" },
      { moon: "Larisa" },
      { moon: "Proteo" },
      { moon: "Halimede" },
      { moon: "Psámate" },
      { moon: "Sao" },
      { moon: "Laomedeia" },
      { moon: "Neso" },
    ],
    isPlanet: true,
    discoveredBy: "Sumerios",
    discoveryDate: "3000 a.C.",
  },
];
